# 自定义变量
my:
  redis-ip: 192.168.59.30


spring:
  redis:
    timeout: 6000ms
    password:
    cluster:
      #设置redis集群的节点信息
      nodes:
        - ${my.redis-ip}:6380
        - ${my.redis-ip}:6381
        - ${my.redis-ip}:6382
        - ${my.redis-ip}:6383
        - ${my.redis-ip}:6384
        - ${my.redis-ip}:6385
      # 最大重定向次数
      max-redirects: 3
    # 配置连接池
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 8
        # 连接池最大等待时间：-1表示没限制
        max-wait: -1ms
        # 连接池最大连接空闲数
        max-idle: 8
        # 连接池最小连接空闲数
        min-idle: 0


