# 自定义变量
my:
  redis-ip: 192.168.59.30

spring:
  redis:
    database: 0
    host: ${my.redis-ip}
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 8
        # 连接池最大等待时间：-1表示没限制
        max-wait: -1ms
        # 连接池最大连接空闲数
        max-idle: 8
        # 连接池最小连接空闲数
        min-idle: 0
server:
  port: 10000

